### ISSUE TITLE
Crash on enabling module

### ISSUE THREAD

**Issue by vampcat** [Terasology/GooeysQuests#24]
As soon as I try to create a game with GQ enabled, my game crashes.

Here is the log:
https://hastebin.com/ugabuqiniz.sql

Other relevant details:
WorldGen used: Perlin
Other modules enabled: Nothing unusual.
OS: Windows 10.

**Comment by flo** [comment]
Strange: The class should be in the Pathfinding module. Current source includes the class that is missing for you: https://github.com/Terasology/Pathfinding/blob/master/src/main/java/org/terasology/pathfinding/components/NPCMovementComponent.java

**Comment by jdrueckert** [comment]
Needs verification if still valid

**Comment by skaldarnar** [comment]
We can start Gooey's Quest atm, so I think this is fixed.
