### ISSUE TITLE
Update wiki to include user guide

### ISSUE THREAD

**Issue by Steampunkery** [Terasology/GooeysQuests#29]
I have created a nice guide to GooeysQuests for new players using lots of pictures. It's hosted on my fork at https://github.com/Steampunkery/GooeysQuests/wiki. Sadly on Github there's no way to PR a wiki. What you can do is clone this repo's wiki and pull my fork's wiki into it. The process is outlined here: https://stackoverflow.com/a/11481887/3142971

**Comment by vampcat** [comment]
Merged the changes.
Thanks for the amazing guide!
